// <auto-generated />
using System;
using CleaningProjectDataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleaningProjectDataAccess.Migrations
{
    [DbContext(typeof(CleaningProjectDbContext))]
    [Migration("20230505084107_mig-hizmetimg")]
    partial class mighizmetimg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleaningProjectModel.Entities.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("MaxValue", 10)
                        .HasAnnotation("MinValue", 5);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins", (string)null);

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            CreatedDate = new DateTime(2023, 5, 5, 11, 41, 7, 440, DateTimeKind.Local).AddTicks(9571),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "admin",
                            Password = "96321.",
                            Surname = "adminss",
                            UserName = "admin963"
                        });
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.Hakkimizda", b =>
                {
                    b.Property<int>("HakkimizdaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HakkimizdaID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Misyonumuz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tanitim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vizyonumuz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HakkimizdaID");

                    b.ToTable("Hakkimzdas", (string)null);

                    b.HasData(
                        new
                        {
                            HakkimizdaID = 1,
                            CreatedDate = new DateTime(2023, 5, 5, 11, 41, 7, 442, DateTimeKind.Local).AddTicks(7797),
                            ImagePath = "path",
                            IsActive = true,
                            IsDeleted = false,
                            Misyonumuz = "misyon önemli",
                            Tanitim = "Hakkmizda",
                            Vizyonumuz = "vizyon öenmli"
                        });
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.Hizmet", b =>
                {
                    b.Property<int>("HizmetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HizmetID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desciption")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("img_path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HizmetID");

                    b.ToTable("Hizmets", (string)null);

                    b.HasData(
                        new
                        {
                            HizmetID = 1,
                            CreatedDate = new DateTime(2023, 5, 5, 11, 41, 7, 441, DateTimeKind.Local).AddTicks(693),
                            Desciption = "Açıklama hizmet detayları ",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ev Temziliği",
                            img_path = "img.png"
                        });
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.Ilce", b =>
                {
                    b.Property<int>("IlceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlceID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IlceID");

                    b.ToTable("Ilces", (string)null);

                    b.HasData(
                        new
                        {
                            IlceID = 1,
                            CreatedDate = new DateTime(2023, 5, 5, 11, 41, 7, 441, DateTimeKind.Local).AddTicks(1137),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Merkez"
                        });
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.Iletisim", b =>
                {
                    b.Property<int>("IletisimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IletisimID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("MaxValue", 11)
                        .HasAnnotation("MinValue", 11);

                    b.Property<string>("ShortAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IletisimID");

                    b.ToTable("Iletisims", (string)null);

                    b.HasData(
                        new
                        {
                            IletisimID = 1,
                            Address = "uzun adress",
                            CreatedDate = new DateTime(2023, 5, 5, 11, 41, 7, 442, DateTimeKind.Local).AddTicks(8516),
                            IsActive = true,
                            IsDeleted = false,
                            Mail = "rey@gmail.com",
                            PhoneNumber = "96321456999",
                            ShortAddress = "Aksaray/Merkez TÜRKİYE"
                        });
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.IsBasvuru", b =>
                {
                    b.Property<int>("IsBasvuruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IsBasvuruID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinishEmployed")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastEmployedCompany")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("MaxValue", 11)
                        .HasAnnotation("MinValue", 11);

                    b.Property<DateTime>("StartEmployed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IsBasvuruID");

                    b.ToTable("IsBasvurus", (string)null);

                    b.HasData(
                        new
                        {
                            IsBasvuruID = 1,
                            Address = "Aksaray/Merkez",
                            CV = "blala bala blaaa",
                            CreatedDate = new DateTime(2023, 5, 5, 11, 41, 7, 441, DateTimeKind.Local).AddTicks(2152),
                            FinishEmployed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastEmployedCompany = "",
                            Mail = "ayse@gmail.com",
                            Name = "Ayşe",
                            PhoneNumber = "05966665214",
                            StartEmployed = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Surname = "Dumankaya"
                        });
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.Personnel", b =>
                {
                    b.Property<int>("PersonnelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonnelID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("MaxValue", 11)
                        .HasAnnotation("MinValue", 11);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("MaxValue", 11)
                        .HasAnnotation("MinValue", 11);

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonnelID");

                    b.HasIndex("IdentityNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Personnels", (string)null);

                    b.HasData(
                        new
                        {
                            PersonnelID = 1,
                            Address = "Aksaray",
                            CreatedDate = new DateTime(2023, 5, 5, 11, 41, 7, 441, DateTimeKind.Local).AddTicks(3869),
                            Email = "anakiz@gmail.com",
                            IdentityNumber = "99966655599",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Anakız",
                            PhoneNumber = "99966633322",
                            SurName = "Soyad"
                        });
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.PersonnelHizmet", b =>
                {
                    b.Property<int>("HizmetID")
                        .HasColumnType("int");

                    b.Property<int>("TeklifID")
                        .HasColumnType("int");

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("HizmetID", "TeklifID", "PersonelID");

                    b.HasIndex("PersonelID");

                    b.HasIndex("TeklifID");

                    b.ToTable("PersonnelHizmets", (string)null);

                    b.HasData(
                        new
                        {
                            HizmetID = 1,
                            TeklifID = 1,
                            PersonelID = 1,
                            CreatedDate = new DateTime(2023, 5, 5, 11, 41, 7, 442, DateTimeKind.Local).AddTicks(1991),
                            IsActive = true,
                            IsDeleted = false,
                            Price = 5,
                            WorkDate = new DateTime(2022, 2, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.SosyalMedya", b =>
                {
                    b.Property<int>("SocialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HesapFA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HesapURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("SocialID");

                    b.ToTable("SosyalMedyas", (string)null);

                    b.HasData(
                        new
                        {
                            SocialID = 1,
                            CreatedDate = new DateTime(2023, 5, 5, 11, 41, 7, 442, DateTimeKind.Local).AddTicks(8231),
                            HesapFA = "<i class=\"fa-brands fa-instagram\"></i>",
                            HesapURL = "https://z-p42.www.instagram.com/reytemizlik/",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.TeklifAl", b =>
                {
                    b.Property<int>("TeklifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeklifID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("MaxValue", 11)
                        .HasAnnotation("MinValue", 11);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TeklifDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeklifHizmetID")
                        .HasColumnType("int");

                    b.Property<int>("TeklifIlceID")
                        .HasColumnType("int");

                    b.HasKey("TeklifID");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("TeklifHizmetID");

                    b.HasIndex("TeklifIlceID");

                    b.ToTable("TeklifAls", (string)null);

                    b.HasData(
                        new
                        {
                            TeklifID = 1,
                            Address = "adress",
                            CreatedDate = new DateTime(2023, 5, 5, 11, 41, 7, 442, DateTimeKind.Local).AddTicks(7421),
                            IsActive = true,
                            IsDeleted = false,
                            Mail = "nur@gmail.com",
                            Name = "Nur",
                            Note = "istenilen hizmet detayları örn m^2 vs vs yazılır",
                            PhoneNumber = "33322211144",
                            Surname = "Al",
                            TeklifDate = new DateTime(2023, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TeklifHizmetID = 1,
                            TeklifIlceID = 1
                        });
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.PersonnelHizmet", b =>
                {
                    b.HasOne("CleaningProjectModel.Entities.Hizmet", "Hizmet")
                        .WithMany("PersonnelHizmets")
                        .HasForeignKey("HizmetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleaningProjectModel.Entities.Personnel", "Personnel")
                        .WithMany("PersonnelHizmets")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleaningProjectModel.Entities.TeklifAl", "TeklifAl")
                        .WithMany("PersonnelHizmets")
                        .HasForeignKey("TeklifID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hizmet");

                    b.Navigation("Personnel");

                    b.Navigation("TeklifAl");
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.TeklifAl", b =>
                {
                    b.HasOne("CleaningProjectModel.Entities.Hizmet", "Hizmet")
                        .WithMany("TeklifAls")
                        .HasForeignKey("TeklifHizmetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleaningProjectModel.Entities.Ilce", "Ilce")
                        .WithMany("TeklifAls")
                        .HasForeignKey("TeklifIlceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hizmet");

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.Hizmet", b =>
                {
                    b.Navigation("PersonnelHizmets");

                    b.Navigation("TeklifAls");
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.Ilce", b =>
                {
                    b.Navigation("TeklifAls");
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.Personnel", b =>
                {
                    b.Navigation("PersonnelHizmets");
                });

            modelBuilder.Entity("CleaningProjectModel.Entities.TeklifAl", b =>
                {
                    b.Navigation("PersonnelHizmets");
                });
#pragma warning restore 612, 618
        }
    }
}
